language: node_js
node_js:
- 6.9.5
install:
- npm install
script:
- npm run build
addons:
  ssh_known_hosts:
  - simpixel.io
before_deploy:
- openssl aes-256-cbc -K $encrypted_571d7fdf2a62_key -iv $encrypted_571d7fdf2a62_iv
  -in ./deploy/id_simpixel.enc -out ./deploy/id_simpixel -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy/id_simpixel
- ssh-add ./deploy/id_simpixel
deploy:
# deploy to beta on ALL commits
- provider: script
  skip_cleanup: true
  script: rsync -rav --delete $TRAVIS_BUILD_DIR/dist/ simpixel@simpixel.io:/home/simpixel/beta.simpixel.io/
  on:
    all_branches: true
# deploy to production on tag creation (only happens when release is created)
- provider: script
  skip_cleanup: true
  script: rsync -rav --delete $TRAVIS_BUILD_DIR/dist/ simpixel@simpixel.io:/home/simpixel/simpixel.io/
  on:
    tags: true
