language: node_js
node_js:
- 6.9.5
# before_install:
# - openssl aes-256-cbc -K $encrypted_571d7fdf2a62_key -iv $encrypted_571d7fdf2a62_iv
#   -in ./deploy/id_simpixel.enc -out ./deploy/id_simpixel -d
install:
- npm install
script:
- npm run build

before_deploy:
- openssl aes-256-cbc aes-256-cbc -K $encrypted_571d7fdf2a62_key -iv $encrypted_571d7fdf2a62_iv -in ./deploy/id_simpixel.enc -out /tmp/id_simpixel -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_simpixel
- ssh-add /tmp/id_simpixel

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -rav --delete $TRAVIS_BUILD_DIR/dist/ simpixel@simpixel.io:/home/simpixel/beta.simpixel.io/
    on:
      all_branches: true
